#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fastnumbers
Version  : 3.0.0
Release  : 7
URL      : https://files.pythonhosted.org/packages/75/98/cfaf907c592f55f3830d7a2a68048800f1320f40fed5ba65e0756432ff22/fastnumbers-3.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/75/98/cfaf907c592f55f3830d7a2a68048800f1320f40fed5ba65e0756432ff22/fastnumbers-3.0.0.tar.gz
Summary  : Super-fast and clean conversions to numbers.
Group    : Development/Tools
License  : MIT
Requires: fastnumbers-license = %{version}-%{release}
Requires: fastnumbers-python = %{version}-%{release}
Requires: fastnumbers-python3 = %{version}-%{release}
Requires: hypothesis
Requires: pyparsing
Requires: six
Requires: sortedcontainers
Requires: zipp
BuildRequires : buildreq-distutils3
BuildRequires : hypothesis
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyparsing
BuildRequires : pytest
BuildRequires : six
BuildRequires : sortedcontainers
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zipp

%description
# Development Collateral
This file contains some files useful for development.
- `astyle.cfg` - Configuration settings for [astyle](http://astyle.sourceforge.net/).
- `bump.py` - Execute `bumpversion` then post-processes the CHANGELOG to handle corner-cases
that `bumpversion` cannot. Requires [`bump2version`](https://github.com/c4urself/bump2version),
which is the maintained fork of [`bumpversion`](https://github.com/peritus/bumpversion).
Not intended to be called directly, but rather by `tox -e bump`.
- `ci-install-python.bash` - Code to install Python on Windows in Travis-CI.
- `ci-update-path.bash` - Sourcing this file in Travis-CI will ensure Python is
on the PATH in Windows.
- `clean.py` - This file cleans most files that are created during development.
Run in the project home directory.
Not intended to be called directly, but rather by `tox -e clean`.
- `patch_doctest.py` -
The [doctest](https://docs.python.org/3/library/doctest.html) module
from the Python standard library has an interesting limitation
whereby it cannot run tests on extension modules. This file
makes a local copy of `doctest.py` and patches it to be able to run
on extension modules.
- `requirements.in` - Our direct requirements to run tests.
- `requirements.txt` - All pinned requirements to run tests.
- `run_coverage.sh` - A small shell one-liner placed into a file that
will compile `fastnumbers`, run all tests, then run `lcov` and
`genhtml` to create an HTML coverage report. Only tested on OSX.

%package license
Summary: license components for the fastnumbers package.
Group: Default

%description license
license components for the fastnumbers package.


%package python
Summary: python components for the fastnumbers package.
Group: Default
Requires: fastnumbers-python3 = %{version}-%{release}

%description python
python components for the fastnumbers package.


%package python3
Summary: python3 components for the fastnumbers package.
Group: Default
Requires: python3-core
Provides: pypi(fastnumbers)

%description python3
python3 components for the fastnumbers package.


%prep
%setup -q -n fastnumbers-3.0.0
cd %{_builddir}/fastnumbers-3.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582922821
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fastnumbers
cp %{_builddir}/fastnumbers-3.0.0/LICENSE %{buildroot}/usr/share/package-licenses/fastnumbers/b8aa28c077d487de890d23ada4f3ebc046681eba
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fastnumbers/b8aa28c077d487de890d23ada4f3ebc046681eba

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
