#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fastnumbers
Version  : 2.2.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/15/3f/80483ecd647f2f83ef355f669eacf712aa437ec1196150d2e8b1e87e1c95/fastnumbers-2.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/15/3f/80483ecd647f2f83ef355f669eacf712aa437ec1196150d2e8b1e87e1c95/fastnumbers-2.2.1.tar.gz
Summary  : Super-fast and clean conversions to numbers.
Group    : Development/Tools
License  : MIT
Requires: fastnumbers-python = %{version}-%{release}
Requires: fastnumbers-python3 = %{version}-%{release}
Requires: hypothesis
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
# Development Collateral
This file contains some files useful for development.
- `astyle.cfg` - Configuration settings for [astyle](http://astyle.sourceforge.net/).
- `build.cmd` - Used to build and run tests on Windows. Shamelessly
stolen from https://packaging.python.org/appveyor/#support-scripts.
- `bump.sh` - Execute `bumpversion` then post-processes the CHANGELOG to handle corner-cases
that `bumpversion` cannot. Requires [`bump2version`](https://github.com/c4urself/bump2version),
which is the maintained fork of [`bumpversion`](https://github.com/peritus/bumpversion).
- `clean.sh` - This file cleans most files that are created during development.
Run in the project home directory.
- `fmt.sh` - This file executes [astyle](http://astyle.sourceforge.net/) then [black](https://black.readthedocs.io/en/stable/).
- `patch_doctest.py` -
The [doctest](https://docs.python.org/3/library/doctest.html) module
from the Python standard library has an interesting limitation
whereby it cannot run tests on extension modules. This file
makes a local copy of `doctest.py` and patches it to be able to run
on extension modules.
- `requirements.txt` - Requirements to run tests
- `run_coverage.sh` - A small shell one-liner placed into a file that
will compile `fastnumbers`, run all tests, then run `lcov` and
`genhtml` to create an HTML coverage report. Only tested on OSX.

%package python
Summary: python components for the fastnumbers package.
Group: Default
Requires: fastnumbers-python3 = %{version}-%{release}

%description python
python components for the fastnumbers package.


%package python3
Summary: python3 components for the fastnumbers package.
Group: Default
Requires: python3-core

%description python3
python3 components for the fastnumbers package.


%prep
%setup -q -n fastnumbers-2.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556217414
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
