#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fastnumbers
Version  : 3.1.0
Release  : 9
URL      : https://files.pythonhosted.org/packages/c9/8c/eb150c91beabdf4ac44d1aec8237709ca1593c615f6cd677914d4c3a2bdb/fastnumbers-3.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c9/8c/eb150c91beabdf4ac44d1aec8237709ca1593c615f6cd677914d4c3a2bdb/fastnumbers-3.1.0.tar.gz
Summary  : Super-fast and clean conversions to numbers.
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: fastnumbers-python = %{version}-%{release}
Requires: fastnumbers-python3 = %{version}-%{release}
Requires: hypothesis
Requires: pyparsing
Requires: six
Requires: sortedcontainers
Requires: zipp
BuildRequires : buildreq-distutils3
BuildRequires : hypothesis
BuildRequires : pep517
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyparsing
BuildRequires : pytest
BuildRequires : python-build
BuildRequires : six
BuildRequires : sortedcontainers
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zipp

%description
===========

%package python
Summary: python components for the fastnumbers package.
Group: Default
Requires: fastnumbers-python3 = %{version}-%{release}

%description python
python components for the fastnumbers package.


%package python3
Summary: python3 components for the fastnumbers package.
Group: Default
Requires: python3-core
Provides: pypi(fastnumbers)

%description python3
python3 components for the fastnumbers package.


%prep
%setup -q -n fastnumbers-3.1.0
cd %{_builddir}/fastnumbers-3.1.0

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629260040
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
export MAKEFLAGS=%{?_smp_mflags}
if [ ! -f setup.py ]; then
printf "#!/usr/bin/env python\nfrom setuptools import setup\nsetup()" > setup.py
chmod +x setup.py
python3 setup.py build
else
python3 setup.py build
fi

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
